import { BASICTILES_COLS, frame } from "./tileset";

export enum Tile {
  Grass = "grass",
  GrassFlower = "grass_flower",
  GrassTuft = "grass_tuft",
  Water = "water",
  Sand = "sand",
  Path = "path",
  Tree = "tree",
  BushRound = "bush_round",
  BushSpiky = "bush_spiky",
  HedgeTopiary = "hedge_topiary",
  Fence = "fence",
  HouseWall = "house_wall",
  HouseDoor = "house_door",
  HouseWindow = "house_window",
  Well = "well",
  Chest = "chest",
  GateCornerTL = "gate_corner_tl",
  GateEdgeT = "gate_edge_t",
  GateCornerTR = "gate_corner_tr",
  GateWallL = "gate_wall_l",
  GateOpening = "gate_opening",
  GateWallR = "gate_wall_r",
  GateCornerBL = "gate_corner_bl",
  GateEdgeB = "gate_edge_b",
  GateCornerBR = "gate_corner_br",
}

/** basictiles.png is an 8-col x 15-row sheet of 16x16 tiles. */
export const TILE_FRAMES: Record<Tile, number> = {
  [Tile.Grass]: frame(1, 3, BASICTILES_COLS),
  [Tile.GrassFlower]: frame(1, 4, BASICTILES_COLS),
  [Tile.GrassTuft]: frame(8, 0, BASICTILES_COLS),
  [Tile.Water]: frame(1, 5, BASICTILES_COLS),
  [Tile.Sand]: frame(1, 2, BASICTILES_COLS),
  [Tile.Path]: frame(9, 1, BASICTILES_COLS),
  [Tile.Tree]: frame(3, 6, BASICTILES_COLS),
  [Tile.BushRound]: frame(2, 3, BASICTILES_COLS),
  [Tile.BushSpiky]: frame(2, 4, BASICTILES_COLS),
  [Tile.HedgeTopiary]: frame(11, 4, BASICTILES_COLS),
  [Tile.Fence]: frame(11, 0, BASICTILES_COLS),
  [Tile.HouseWall]: frame(0, 4, BASICTILES_COLS),
  [Tile.HouseDoor]: frame(6, 0, BASICTILES_COLS),
  [Tile.HouseWindow]: frame(7, 1, BASICTILES_COLS),
  [Tile.Well]: frame(3, 7, BASICTILES_COLS),
  [Tile.Chest]: frame(4, 3, BASICTILES_COLS),
  [Tile.GateCornerTL]: frame(3, 0, BASICTILES_COLS),
  [Tile.GateEdgeT]: frame(3, 1, BASICTILES_COLS),
  [Tile.GateCornerTR]: frame(3, 2, BASICTILES_COLS),
  [Tile.GateWallL]: frame(4, 0, BASICTILES_COLS),
  [Tile.GateOpening]: frame(4, 1, BASICTILES_COLS),
  [Tile.GateWallR]: frame(4, 2, BASICTILES_COLS),
  [Tile.GateCornerBL]: frame(5, 0, BASICTILES_COLS),
  [Tile.GateEdgeB]: frame(5, 1, BASICTILES_COLS),
  [Tile.GateCornerBR]: frame(5, 2, BASICTILES_COLS),
};

export const SOLID_TILES = new Set<Tile>([
  Tile.Water,
  Tile.Tree,
  Tile.BushRound,
  Tile.BushSpiky,
  Tile.HedgeTopiary,
  Tile.Fence,
  Tile.HouseWall,
  Tile.HouseDoor,
  Tile.HouseWindow,
  Tile.Well,
  Tile.Chest,
  Tile.GateCornerTL,
  Tile.GateEdgeT,
  Tile.GateCornerTR,
  Tile.GateWallL,
  Tile.GateOpening,
  Tile.GateWallR,
  Tile.GateCornerBL,
  Tile.GateEdgeB,
  Tile.GateCornerBR,
]);

export function isSolid(tile: Tile): boolean {
  return SOLID_TILES.has(tile);
}
